# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RoomItems(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, color=None, link=None):  # noqa: E501
        """RoomItems - a model defined in OpenAPI

        :param type: The type of this RoomItems.  # noqa: E501
        :type type: str
        :param color: The color of this RoomItems.  # noqa: E501
        :type color: str
        :param link: The link of this RoomItems.  # noqa: E501
        :type link: str
        """
        self.openapi_types = {
            'type': str,
            'color': str,
            'link': str
        }

        self.attribute_map = {
            'type': 'type',
            'color': 'color',
            'link': 'link'
        }

        self._type = type
        self._color = color
        self._link = link

    @classmethod
    def from_dict(cls, dikt) -> 'RoomItems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The room_items of this RoomItems.  # noqa: E501
        :rtype: RoomItems
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this RoomItems.


        :return: The type of this RoomItems.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RoomItems.


        :param type: The type of this RoomItems.
        :type type: str
        """

        self._type = type

    @property
    def color(self):
        """Gets the color of this RoomItems.


        :return: The color of this RoomItems.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this RoomItems.


        :param color: The color of this RoomItems.
        :type color: str
        """

        self._color = color

    @property
    def link(self):
        """Gets the link of this RoomItems.


        :return: The link of this RoomItems.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this RoomItems.


        :param link: The link of this RoomItems.
        :type link: str
        """

        self._link = link
