# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.room_items import RoomItems
from openapi_server import util

from openapi_server.models.room_items import RoomItems  # noqa: E501

class Room(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """Room - a model defined in OpenAPI

        :param items: The items of this Room.  # noqa: E501
        :type items: List[RoomItems]
        """
        self.openapi_types = {
            'items': List[RoomItems]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Room':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The room of this Room.  # noqa: E501
        :rtype: Room
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this Room.


        :return: The items of this Room.
        :rtype: List[RoomItems]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Room.


        :param items: The items of this Room.
        :type items: List[RoomItems]
        """

        self._items = items
